export const membersTitle = ['#', 'full name', 'direction', 'education', 'start', 'age', ''];
export const membersTasksTitle = ['#', 'name', 'start', 'deadline', 'status', '', 'available only for admin'];
export const membersTasksTitleForMembers = ['#', 'name', 'start', 'deadline', 'status', ''];
export const memberProgressTitle = ['#', 'task', 'note', 'date'];
export const taskManagementTitle = ['#', 'name', 'start', 'deadline', ''];
export const tasksTrackTitle = ['#', 'task', 'note', 'date', ''];
export const emailRegexp = /^\w+([.-]?\w+)*@\w+([.-]?\w+)*(\.\w{2,3})+$/;
export const latinLetterRegexp = /^[a-zA-Z]+$/;
export const phoneNumberRegexp = /^[+]*[(]{0,1}[0-9]{1,4}[)]{0,1}[-\s./0-9]*$/;
